# fly.toml app configuration file generated for dig-app on 2025-07-16T20:44:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dig-app'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

# [deploy]
#   release_command = 'npx prisma migrate deploy'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
